### ISSUE TITLE
namespaced-openvpn argument issue?

### ISSUE THREAD

**Issue by Denio888** [slingamn/namespaced-openvpn#23] opened 2019-07-06 09:30 UTC
Hi, it seems there is a little bug inside the namespaced-openvpn script.
It concerns this section:

namespaced-openvpn can also be used to "stack" VPN tunnels, e.g.,
sudo namespaced-openvpn --namespace level1 --config ./config1
sudo ip netns exec level1 namespaced-openvpn --namespace level2 --config ./config2

I get this error:
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.4.4)
Use --help for more information.

I think the script tries to pass the --namespace argument to openvpn, instead of using it in the namespaced-openvpn script.
2.4.4 is my openvpn version.

**Comment by slingamn** [comment] 2019-07-07 01:53
I'm unable to reproduce this locally (my system has openvpn 2.4.6, but that shouldn't make a difference). Are you using the latest version of the namespaced-openvpn script? Also, are you sure that the sudoers path (`secure_path` in `/etc/sudoers` or `/etc/sudoers.d`) is pointing you to the correct version of namespaced-openvpn?

**Comment by slingamn** [comment] 2019-07-07 01:54
`sudo which namespaced-openvpn` should help with verifying that you're running the expected script.

**Comment by Denio888** [comment] 2019-07-07 13:33
Thx for your reply, testing and fast help.
I stripped it down and tried to run it with 2 console windows.
Then it is working perfectly, so i think again i have a problem with the general unix syntax and it is not a script error.
I was trying to run both commands in 1 console window, but that seems a bit tricky, so i stay with 2 console windows.

If i find out how to run it in 1 console window i will post the syntax here.

**Comment by slingamn** [comment] 2019-07-07 13:47
Thanks! I'll close this issue for now, but feel free to open a new one if anything new comes to light.

**Closed by slingamn** 2019-07-07 13:47 UTC
